#Server
server:
  port: 8764
#freemarker
spring:
  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  application:
    name: disk-web
  servlet:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 5000Mb
#logger
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/diskLog/file
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

