#Server
server:
  port: 8763
#freemarker
spring:
  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  application:
    name: disk-web
  servlet:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 5000Mb
  redis:
    database: 0           # Redis服务器数据库
    host: 47.94.88.204    # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password: TRX.0721      # Redis服务器连接密码（默认为空）
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
#logger
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/diskLog/file
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#文件临时保存路径
file:
  upload: D:/diskLog/temp