#Server
server:
  port: 8764
#freemarker
spring:
  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: false
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
#logger
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/diskLog/file
#feien
feign:
  compression:
    request:
      enabled: true
    response:
      enabled：true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false